backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"      # where the files are stored in your repo
public_folder: "/images/uploads"    # how the site references them in HTML/Markdown

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
