backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"      # where uploaded images are stored in repo
public_folder: "/images/uploads"    # how images are referenced on the site

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"                 # create posts here instead of _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Featured Image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
