name: Update posts index
on:
  push:
    paths:
      - '_posts/**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build index.json
        run: |
          echo "[" > _posts/index.json
          first=true
          for f in _posts/*.md; do
            title=$(grep '^title:' "$f" | head -n1 | cut -d':' -f2- | xargs)
            date=$(grep '^date:' "$f" | head -n1 | cut -d':' -f2- | xargs)
            image=$(grep '^image:' "$f" | head -n1 | cut -d':' -f2- | xargs)
            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> _posts/index.json
            fi
            printf '{"title": "%s", "date": "%s", "file": "%s"%s}' \
              "$title" "$date" "$f" \
              $( [ -n "$image" ] && printf ', "image": "%s"' "$image" )
            >> _posts/index.json
          done
          echo "]" >> _posts/index.json

      - name: Commit and push
        run: |
          git config user.name "actions-user"
          git config user.email "actions@github.com"
          git add _posts/index.json
          git commit -m "Update _posts index" || echo "No changes"
          git push
