name: Update posts index

on:
  push:
    paths:
      - "posts/*.md"
  workflow_dispatch: {}   # add a Run button in the Actions tab

permissions:
  contents: write         # let the workflow commit to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate posts/index.json
        shell: bash
        run: |
          mkdir -p posts
          mapfile -t files < <(ls -1 posts/*.md 2>/dev/null | sort)
          if [ ${#files[@]} -eq 0 ]; then
            echo "[]" > posts/index.json
          else
            {
              printf '['
              first=1
              for f in "${files[@]}"; do
                base=$(basename "$f")
                if [ $first -eq 0 ]; then printf ','; fi
                printf '"%s"' "$base"
                first=0
              done
              printf ']\n'
            } > posts/index.json
          fi
          echo "Generated posts/index.json:"
          cat posts/index.json

      - name: Commit and push changes
        run: |
          if git diff --quiet posts/index.json; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/index.json
          git commit -m "Auto-update posts/index.json"
          git push
