name: Update posts index

on:
  push:
    branches:
      - main
    paths:
      - "_posts/**/*.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate index.json
        shell: bash
        run: |
          set -e
          echo "[" > _posts/index.json
          first=true
          for f in _posts/*.md; do
            # Extract fields from YAML frontmatter
            title=$(grep -m1 '^title:' "$f" | sed 's/^title:[[:space:]]*//')
            date=$(grep -m1 '^date:' "$f" | sed 's/^date:[[:space:]]*//')
            image=$(grep -m1 '^image:' "$f" | sed 's/^image:[[:space:]]*//')

            if [ -n "$title" ] && [ -n "$date" ]; then
              if [ "$first" = false ]; then
                echo "," >> _posts/index.json
              fi
              first=false
              json="{\"title\": \"$title\", \"date\": \"$date\", \"file\": \"$f\""
              [ -n "$image" ] && json="$json, \"image\": \"$image\""
              json="$json}"
              echo "  $json" >> _posts/index.json
            fi
          done
          echo "]" >> _posts/index.json
          cat _posts/index.json

      - name: Commit and push index.json
        run: |
          git config user.name "actions-user"
          git config user.email "actions@github.com"
          git add _posts/index.json
          git diff --cached --quiet || git commit -m "Auto-update _posts index"
          git push
