name: Update index.json

on:
  push:
    branches:
      - main
    paths:
      - "_posts/*.md"

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate index.json
        run: |
          mkdir -p _posts
          echo "[" > _posts/index.json
          first=true
          for file in _posts/*.md; do
            [ -e "$file" ] || continue
            title=$(grep -m 1 '^title:' "$file" | cut -d '"' -f2)
            date=$(grep -m 1 '^date:' "$file" | awk '{print $2}')
            if [ "$first" = true ]; then first=false; else echo "," >> _posts/index.json; fi
            echo "  {\"title\": \"$title\", \"date\": \"$date\", \"file\": \"$file\"}" >> _posts/index.json
          done
          echo "]" >> _posts/index.json

      - name: Commit and push index.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _posts/index.json
          git commit -m "Update _posts index" || exit 0
          git push
