name: Update index.json on new posts

on:
  push:
    branches:
      - '**'                # trigger on any branch
    paths:
      - "_posts/**/*.md"    # any markdown file in _posts
  workflow_dispatch:         # allows manual run from Actions tab

permissions:
  contents: write
  actions: write
  id-token: write

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repo contents
        run: |
          echo "=== Root ==="
          ls -al
          echo "=== _posts ==="
          ls -al _posts || echo "_posts missing"

      - name: Generate valid _posts/index.json
        shell: bash
        run: |
          set -e
          mkdir -p _posts
          echo "[" > _posts/index.json
          first=true
          shopt -s nullglob

          for f in _posts/*.md; do
            echo "Processing $f"
            title=$(grep -m1 '^title:' "$f" | sed 's/^title:[[:space:]]*//')
            date=$(grep -m1 '^date:' "$f" | sed 's/^date:[[:space:]]*//')
            image=$(grep -m1 '^image:' "$f" | sed 's/^image:[[:space:]]*//')

            [ -z "$title" ] && title="Untitled"
            [ -z "$date" ] && date=$(date -Iseconds)

            json="{\"title\": \"${title//\"/\\\"}\", \"date\": \"${date//\"/\\\"}\", \"file\": \"${f//\"/\\\"}\""
            if [ -n "$image" ]; then
              json="$json, \"image\": \"${image//\"/\\\"}\""
            fi
            json="$json}"

            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> _posts/index.json
            fi
            echo "  $json" >> _posts/index.json
          done

          echo "]" >> _posts/index.json
          echo "=== index.json generated ==="
          cat _posts/index.json

      - name: Commit and push index.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/index.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update index.json from workflow"
            git push
          fi

