name: Update Index

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rebuild _posts/index.json
        run: |
          echo "[" > _posts/index.json
          first=true
          for file in _posts/*.md; do
            [ "$first" = true ] || echo "," >> _posts/index.json
            first=false
            title=$(grep -m1 '^title:' "$file" | sed 's/title:[[:space:]]*//')
            date=$(echo "$file" | sed -E 's#_posts/([0-9-]+)-.*#\1#')
            echo "  {\"title\": \"$title\", \"date\": \"$date\", \"file\": \"$file\"}" >> _posts/index.json
          done
          echo "]" >> _posts/index.json

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/index.json
          git diff --cached --quiet || git commit -m "Auto-update index.json"
          git push
