name: Update index.json on new posts

on:
  push:
    branches:
      - main
    paths:
      - "_posts/**/*.md"
      - ".github/workflows/update-index.yml"

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate index.json
        shell: bash
        run: |
          set -e
          echo "[" > _posts/index.json
          first=true
          for f in _posts/*.md; do
            title=$(grep -m1 '^title:' "$f" | sed 's/^title:[[:space:]]*//')
            date=$(grep -m1 '^date:' "$f" | sed 's/^date:[[:space:]]*//')
            image=$(grep -m1 '^image:' "$f" | sed 's/^image:[[:space:]]*//')
            [ -z "$title" ] && title="Untitled"
            [ -z "$date" ] && date=$(date -Iseconds)

            json="{\"title\": \"${title//\"/\\\"}\", \"date\": \"${date//\"/\\\"}\", \"file\": \"${f//\"/\\\"}\""
            if [ -n "$image" ]; then
              json="$json, \"image\": \"${image//\"/\\\"}\""
            fi
            json="$json}"

            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> _posts/index.json
            fi
            echo "  $json" >> _posts/index.json
          done
          echo "]" >> _posts/index.json

      - name: Commit and push index.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/index.json
          git diff --cached --quiet && echo "No visible changes" || (git commit -m "Auto-update index.json" && git push)
