name: Auto-update posts/index.json

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rebuild-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure posts directory exists
        run: |
          if [ ! -d "posts" ]; then
            echo "Creating missing posts directory..."
            mkdir posts
          fi

      - name: Generate new index.json
  shell: bash
  run: |
    set +e
    echo "[" > posts/index.json
    first=true

    echo "Finding markdown files in posts..."
    ls -la posts || echo "No posts folder found!"
    find posts -maxdepth 1 -type f -name "*.md" | sort

    for file in $(find posts -maxdepth 1 -type f -name "*.md" | sort); do
      echo "Processing $file"
      title=$(grep -m1 "^title:" "$file" | sed 's/^title:[[:space:]]*//;s/"//g')
      date=$(grep -m1 "^date:" "$file" | sed 's/^date:[[:space:]]*//;s/"//g')
      image=$(grep -m1 "^image:" "$file" | sed 's/^image:[[:space:]]*//;s/"//g')
      filename=$(basename "$file")

      if [ "$first" = true ]; then
        first=false
      else
        echo "," >> posts/index.json
      fi

      echo "  {" >> posts/index.json
      echo "    \"title\": \"$title\"," >> posts/index.json
      echo "    \"date\": \"$date\"," >> posts/index.json
      echo "    \"image\": \"$image\"," >> posts/index.json
      echo "    \"filename\": \"$filename\"" >> posts/index.json
      echo -n "  }" >> posts/index.json
    done

    echo "]" >> posts/index.json

      - name: Debug output
        run: cat posts/index.json

      - name: Commit and push index.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/index.json

          if ! git diff --cached --quiet; then
            git commit -m "Auto-update posts/index.json"
            git push
          else
            echo "No changes to commit."
          fi
