name: Update index.json on new posts

on:
  push:
    branches:
      - main
    paths:
      - "_posts/**/*.md"
      - ".github/workflows/update-index.yml"

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate index.json
        run: |
          echo "[" > _posts/index.json
          first=true
          for f in _posts/*.md; do
            # Extract frontmatter values
            title=$(grep -m1 '^title:' "$f" | sed 's/^title:[[:space:]]*//')
            date=$(grep -m1 '^date:' "$f" | sed 's/^date:[[:space:]]*//')
            image=$(grep -m1 '^image:' "$f" | sed 's/^image:[[:space:]]*//')
            if [ "$first" = true ]; then first=false; else echo "," >> _posts/index.json; fi
            echo "{\"title\": \"${title}\", \"date\": \"${date}\", \"image\": \"${image}\", \"file\": \"${f}\"}" >> _posts/index.json
          done
          echo "]" >> _posts/index.json

      - name: Check for changes
        run: |
          git diff --quiet _posts/index.json || echo "index.json changed"

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/index.json
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update index.json from workflow"
            git push
          else
            echo "No changes to commit."
          fi

